---
title: 'Introduction'
teaching: 10
exercises: 2
---


The hackathon invites participants to explore how digital data sources can come together to address research questions associated with global challenges and cultural heritage. The event will be the first of a series of activities collaboratively exploring opportunities to work with available data by leveraging A&H Digital Research Infrastructure (DRI) to address research questions and pilot innovative research directions.  During the hackathon, participants will gain insights into UKRI-funded data services, community-generated code and innovative AI-assisted methods with the support of technical professionals.  

The integration of data from heterogeneous sources is a particular focus of these scenarios, as the hackathon aims to explore the infrastructures, tools, and knowledge required for this. Hence, participants are invited to reflect on the strengths and needs of these data services, the availability of tools, and the knowledge barriers to developing research approaches based on this integration of data. The role of Artificial Intelligence models in supporting coding and agentic processes in software development is of further interest.

