---
title: 'Scenarios'
teaching: 10
exercises: 2
---

# Scenarios
The scenarios below can inform the development of workflows or research ideas. They aim to leverage the availability and integration of relevant information from different data services. 

## Prioritising emergency recording of cultural heritage 
Coastal cultural heritage—including archaeological sites, historic buildings, and maritime landscapes—is increasingly at risk of erosion, flooding, climate change, and human activity. These threats are often rapid and uneven, making it difficult for heritage professionals to determine where limited resources for documentation and preservation should be focused. Incorporating socio-economic data can also support prioritising areas with social, economic or cultural importance, while also improving equity in heritage preservation. 


## Informing planning of infrastructure affecting cultural heritage

The development of infrastructure around cultural heritage sites presents a complex balance between improving access and safeguarding fragile assets. New transport links and utilities can increase visitor numbers and bring economic benefits to local communities, particularly through tourism. However, these same developments can place significant pressure on heritage sites, leading to physical damage, erosion, and the risks associated with overtourism. Decision-makers often lack a holistic view of how planned or future infrastructure projects will interact with both existing and potential heritage sites.  

## Mitigating the impacts of ageing infrastructure on urban communities 
Listed and historic buildings in urban areas are particularly vulnerable to the impacts of ageing infrastructure, including transport networks, underground utilities, and adjacent buildings. Continuous exposure to vibration from rail and road traffic, alongside ground disturbance from maintenance or redevelopment, can weaken structural integrity, causing cracking, settlement, and material fatigue in historically sensitive fabric. These can have a significant impact on how such buildings are used—often still occupied as homes, workplaces, or community spaces—directly affecting users' lived experience. Understanding how ongoing stress can affect these fragile, historically significant structures can support planning interventions and other mitigation strategies. 

